/**
 * Anthropic (Claude) model IDs — OpenRouter (public). Run script to refresh.
 * Generated by scripts/update-models.ts — do not edit by hand.
 */

import { z } from "zod";

export const MODEL_IDS = {
  CLAUDE_3_HAIKU: "claude-3-haiku",
  CLAUDE_3_5_HAIKU: "claude-3.5-haiku",
  CLAUDE_3_5_SONNET: "claude-3.5-sonnet",
  CLAUDE_3_7_SONNET: "claude-3.7-sonnet",
  CLAUDE_3_7_SONNET_THINKING: "claude-3.7-sonnet:thinking",
  CLAUDE_HAIKU_4_5: "claude-haiku-4.5",
  CLAUDE_OPUS_4: "claude-opus-4",
  CLAUDE_OPUS_4_1: "claude-opus-4.1",
  CLAUDE_OPUS_4_5: "claude-opus-4.5",
  CLAUDE_OPUS_4_6: "claude-opus-4.6",
  CLAUDE_SONNET_4: "claude-sonnet-4",
  CLAUDE_SONNET_4_5: "claude-sonnet-4.5",
  CLAUDE_SONNET_4_6: "claude-sonnet-4.6",
} as const;

export const MODEL_ID_LIST: readonly string[] = Object.values(MODEL_IDS);

export const ModelIdSchema = z.enum([
  "claude-3-haiku",
  "claude-3.5-haiku",
  "claude-3.5-sonnet",
  "claude-3.7-sonnet",
  "claude-3.7-sonnet:thinking",
  "claude-haiku-4.5",
  "claude-opus-4",
  "claude-opus-4.1",
  "claude-opus-4.5",
  "claude-opus-4.6",
  "claude-sonnet-4",
  "claude-sonnet-4.5",
  "claude-sonnet-4.6",
]);

export type ModelId = z.infer<typeof ModelIdSchema>;
