/**
 * Google Gemini model IDs — OpenRouter (public). Run script to refresh.
 * Generated by scripts/update-models.ts — do not edit by hand.
 */

import { z } from "zod";

export const MODEL_IDS = {
  GEMINI_2_0_FLASH_001: "gemini-2.0-flash-001",
  GEMINI_2_0_FLASH_LITE_001: "gemini-2.0-flash-lite-001",
  GEMINI_2_5_FLASH: "gemini-2.5-flash",
  GEMINI_2_5_FLASH_IMAGE: "gemini-2.5-flash-image",
  GEMINI_2_5_FLASH_LITE: "gemini-2.5-flash-lite",
  GEMINI_2_5_FLASH_LITE_PREVIEW_09_2025: "gemini-2.5-flash-lite-preview-09-2025",
  GEMINI_2_5_PRO: "gemini-2.5-pro",
  GEMINI_2_5_PRO_PREVIEW: "gemini-2.5-pro-preview",
  GEMINI_2_5_PRO_PREVIEW_05_06: "gemini-2.5-pro-preview-05-06",
  GEMINI_3_FLASH_PREVIEW: "gemini-3-flash-preview",
  GEMINI_3_PRO_IMAGE_PREVIEW: "gemini-3-pro-image-preview",
  GEMINI_3_PRO_PREVIEW: "gemini-3-pro-preview",
  GEMINI_3_1_FLASH_IMAGE_PREVIEW: "gemini-3.1-flash-image-preview",
  GEMINI_3_1_FLASH_LITE_PREVIEW: "gemini-3.1-flash-lite-preview",
  GEMINI_3_1_PRO_PREVIEW: "gemini-3.1-pro-preview",
  GEMINI_3_1_PRO_PREVIEW_CUSTOMTOOLS: "gemini-3.1-pro-preview-customtools",
  GEMMA_2_27B_IT: "gemma-2-27b-it",
  GEMMA_2_9B_IT: "gemma-2-9b-it",
  GEMMA_3_12B_IT: "gemma-3-12b-it",
  GEMMA_3_12B_IT_FREE: "gemma-3-12b-it:free",
  GEMMA_3_27B_IT: "gemma-3-27b-it",
  GEMMA_3_27B_IT_FREE: "gemma-3-27b-it:free",
  GEMMA_3_4B_IT: "gemma-3-4b-it",
  GEMMA_3_4B_IT_FREE: "gemma-3-4b-it:free",
  GEMMA_3N_E2B_IT_FREE: "gemma-3n-e2b-it:free",
  GEMMA_3N_E4B_IT: "gemma-3n-e4b-it",
  GEMMA_3N_E4B_IT_FREE: "gemma-3n-e4b-it:free",
} as const;

export const MODEL_ID_LIST: readonly string[] = Object.values(MODEL_IDS);

export const ModelIdSchema = z.enum([
  "gemini-2.0-flash-001",
  "gemini-2.0-flash-lite-001",
  "gemini-2.5-flash",
  "gemini-2.5-flash-image",
  "gemini-2.5-flash-lite",
  "gemini-2.5-flash-lite-preview-09-2025",
  "gemini-2.5-pro",
  "gemini-2.5-pro-preview",
  "gemini-2.5-pro-preview-05-06",
  "gemini-3-flash-preview",
  "gemini-3-pro-image-preview",
  "gemini-3-pro-preview",
  "gemini-3.1-flash-image-preview",
  "gemini-3.1-flash-lite-preview",
  "gemini-3.1-pro-preview",
  "gemini-3.1-pro-preview-customtools",
  "gemma-2-27b-it",
  "gemma-2-9b-it",
  "gemma-3-12b-it",
  "gemma-3-12b-it:free",
  "gemma-3-27b-it",
  "gemma-3-27b-it:free",
  "gemma-3-4b-it",
  "gemma-3-4b-it:free",
  "gemma-3n-e2b-it:free",
  "gemma-3n-e4b-it",
  "gemma-3n-e4b-it:free",
]);

export type ModelId = z.infer<typeof ModelIdSchema>;
