/**
 * xAI (Grok) model IDs — OpenRouter (public). Run script to refresh.
 * Generated by scripts/update-models.ts — do not edit by hand.
 */

import { z } from "zod";

export const MODEL_IDS = {
  GROK_3: "grok-3",
  GROK_3_BETA: "grok-3-beta",
  GROK_3_MINI: "grok-3-mini",
  GROK_3_MINI_BETA: "grok-3-mini-beta",
  GROK_4: "grok-4",
  GROK_4_FAST: "grok-4-fast",
  GROK_4_1_FAST: "grok-4.1-fast",
  GROK_CODE_FAST_1: "grok-code-fast-1",
} as const;

/**
 * @deprecated Unread anywhere, and lossier than its source: `readonly string[]` discards the
 * literal union MODEL_IDS already carries. Use `Object.values(MODEL_IDS)`. Removed next major.
 */
export const MODEL_ID_LIST: readonly string[] = Object.values(MODEL_IDS);

export const ModelIdSchema = z.enum([
  "grok-3",
  "grok-3-beta",
  "grok-3-mini",
  "grok-3-mini-beta",
  "grok-4",
  "grok-4-fast",
  "grok-4.1-fast",
  "grok-code-fast-1",
]);

export type ModelId = z.infer<typeof ModelIdSchema>;
