/**
 * Pure helpers for the generated model modules. Kept separate from update-models.ts so they can
 * be unit-tested without the script's top-level main() firing network requests.
 */

/** Derive a constant name from a model id. Not injective: `-`, `.` and every \W char map to `_`. */
export function safeKey(id: string): string {
  return id.replace(/[-.]/g, "_").replace(/\W/g, "_").toUpperCase();
}

/**
 * Map model ids to constant names, failing loudly on a collision.
 *
 * The previous strategy appended an ordinal (`X_2`) in sorted order. Because the suffix depended
 * on set membership rather than on the id, an upstream addition could take a name an existing
 * model already had: `-` sorts before `.`, so publishing `claude-3-5-haiku` alongside
 * `claude-3.5-haiku` would silently repoint the published ANTHROPIC_MODEL_IDS.CLAUDE_3_5_HAIKU
 * at a different model, with no type error. Renaming is a decision a human has to make, so this
 * throws instead of guessing.
 */
export function modelIdEntries(ids: string[]): Record<string, string> {
  const byKey: Record<string, string> = {};
  for (const id of ids) {
    const key = safeKey(id);
    const existing = byKey[key];
    if (existing !== undefined) {
      throw new Error(
        `Model id key collision: "${existing}" and "${id}" both map to ${key}. ` +
          "Disambiguate one of them in the generator before regenerating."
      );
    }
    byKey[key] = id;
  }
  return byKey;
}

/**
 * Render one generated model module.
 *
 * The emitted shape is deliberately unchanged: the schema stays a literal `z.enum([...])` rather
 * than being derived from MODEL_IDS. Deriving it would need an `as [ModelId, ...ModelId[]]`
 * assertion in the package's most safety-critical generated artifact, to guard a desync between
 * two expressions three lines apart in this one function. Not worth the trade.
 */
export function renderModelModule(headerComment: string, ids: string[]): string {
  const entries = modelIdEntries(ids);
  const body = Object.entries(entries)
    .map(([key, id]) => `  ${key}: "${id}",`)
    .join("\n");
  const schemaValues = Object.values(entries)
    .map((id) => `  "${id}"`)
    .join(",\n");

  return `/**
 * ${headerComment}
 * Generated by scripts/update-models.ts — do not edit by hand.
 */

import { z } from "zod";

export const MODEL_IDS = {
${body}
} as const;

export const MODEL_ID_LIST: readonly string[] = Object.values(MODEL_IDS);

export const ModelIdSchema = z.enum([
${schemaValues}
]);

export type ModelId = z.infer<typeof ModelIdSchema>;
`;
}
