/**
 * Fetches available model IDs and writes src/domain/models/*.ts.
 * Run: bun run update-models
 *
 * Public source (no keys): OpenRouter GET https://openrouter.ai/api/v1/models
 * Optional (with keys): Anthropic, OpenAI, Gemini, xAI provider APIs (override OpenRouter data).
 * Env: ANTHROPIC_API_KEY, OPENAI_API_KEY, GEMINI_API_KEY or GOOGLE_API_KEY, XAI_API_KEY
 * Optional: ACP_LLM_CLI_MODELS_DRY_RUN=1 to log only, no write.
 */

import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = fileURLToPath(new URL(".", import.meta.url));
const ROOT = join(__dirname, "..");
const MODELS_DIR = join(ROOT, "src", "domain", "models");
const DRY_RUN = process.env.ACP_LLM_CLI_MODELS_DRY_RUN === "1";

function safeKey(id: string): string {
  return id.replace(/[-.]/g, "_").replace(/\W/g, "_").toUpperCase() || "MODEL";
}

function uniqueKeys(ids: string[]): [string, string][] {
  const seen = new Map<string, number>();
  return ids.map((id) => {
    let key = safeKey(id);
    const count = seen.get(key) ?? 0;
    seen.set(key, count + 1);
    if (count > 0) key = `${key}_${count + 1}`;
    return [key, id] as [string, string];
  });
}

function writeModelConstants(provider: string, modelIds: string[], headerComment: string): void {
  const sorted = [...new Set(modelIds)].filter(Boolean).sort();
  const entries = uniqueKeys(sorted);
  const enumEntries = entries.map(([k, id]) => `  ${k}: "${id}",`);
  const enumBody = enumEntries.join("\n");
  const schemaValues = sorted.map((id) => `  "${id}"`).join(",\n");
  const content = `/**
 * ${headerComment}
 * Generated by scripts/update-models.ts — do not edit by hand.
 */

import { z } from "zod";

export const MODEL_IDS = {
${enumBody}
} as const;

export const MODEL_ID_LIST: readonly string[] = Object.values(MODEL_IDS);

export const ModelIdSchema = z.enum([
${schemaValues}
]);

export type ModelId = z.infer<typeof ModelIdSchema>;
`;

  const outPath = join(MODELS_DIR, `${provider}.models.ts`);
  if (DRY_RUN) {
    console.log(`[dry-run] would write ${outPath} (${sorted.length} models)`);
    return;
  }
  mkdirSync(MODELS_DIR, { recursive: true });
  writeFileSync(outPath, content, "utf8");
  console.log(`Wrote ${outPath} (${sorted.length} models)`);
}

async function fetchAnthropic(): Promise<string[]> {
  const key = process.env.ANTHROPIC_API_KEY;
  if (!key) {
    console.warn("ANTHROPIC_API_KEY not set, skipping Anthropic");
    return [];
  }
  const out: string[] = [];
  let afterId: string | undefined;
  do {
    const url = new URL("https://api.anthropic.com/v1/models");
    if (afterId) url.searchParams.set("after_id", afterId);
    const res = await fetch(url.toString(), {
      headers: {
        "anthropic-version": "2023-06-01",
        "x-api-key": key,
      },
    });
    if (!res.ok) {
      console.warn("Anthropic models fetch failed:", res.status, await res.text());
      break;
    }
    const data = (await res.json()) as {
      data?: { id?: string }[];
      last_id?: string;
      has_more?: boolean;
    };
    const list = data.data ?? [];
    for (const m of list) if (m.id) out.push(m.id);
    afterId = data.has_more ? data.last_id : undefined;
  } while (afterId);
  return out;
}

async function fetchOpenAI(): Promise<string[]> {
  const key = process.env.OPENAI_API_KEY;
  if (!key) {
    console.warn("OPENAI_API_KEY not set, skipping OpenAI");
    return [];
  }
  const out: string[] = [];
  let url: string | null = "https://api.openai.com/v1/models";
  while (url) {
    const res = await fetch(url, {
      headers: { Authorization: `Bearer ${key}` },
    });
    if (!res.ok) {
      console.warn("OpenAI models fetch failed:", res.status, await res.text());
      break;
    }
    const data = (await res.json()) as {
      data?: { id?: string }[];
      next?: string | null;
    };
    const list = data.data ?? [];
    for (const m of list) if (m.id) out.push(m.id);
    url = data.next ?? null;
  }
  return out;
}

async function fetchGemini(): Promise<string[]> {
  const key = process.env.GEMINI_API_KEY ?? process.env.GOOGLE_API_KEY;
  if (!key) {
    console.warn("GEMINI_API_KEY / GOOGLE_API_KEY not set, skipping Gemini");
    return [];
  }
  const out: string[] = [];
  let pageToken: string | undefined;
  do {
    const url = new URL("https://generativelanguage.googleapis.com/v1beta/models");
    url.searchParams.set("key", key);
    if (pageToken) url.searchParams.set("pageToken", pageToken);
    const res = await fetch(url.toString());
    if (!res.ok) {
      console.warn("Gemini models fetch failed:", res.status, await res.text());
      break;
    }
    const data = (await res.json()) as {
      models?: { name?: string }[];
      nextPageToken?: string;
    };
    const list = data.models ?? [];
    for (const m of list) {
      const name = m.name;
      if (name?.startsWith("models/")) out.push(name.replace(/^models\//, ""));
    }
    pageToken = data.nextPageToken;
  } while (pageToken);
  return out;
}

async function fetchXAI(): Promise<string[]> {
  const key = process.env.XAI_API_KEY;
  if (!key) {
    console.warn("XAI_API_KEY not set, skipping xAI");
    return [];
  }
  const res = await fetch("https://api.x.ai/v1/models", {
    headers: { Authorization: `Bearer ${key}` },
  });
  if (!res.ok) {
    console.warn("xAI models fetch failed:", res.status, await res.text());
    return [];
  }
  const data = (await res.json()) as { data?: { id?: string }[] };
  const list = data.data ?? [];
  return list.map((m) => m.id).filter((id): id is string => Boolean(id));
}

/** OpenRouter provider prefix -> our provider key */
const OPENROUTER_PREFIX: Record<string, string> = {
  anthropic: "anthropic",
  openai: "openai",
  google: "gemini",
  "x-ai": "xai",
  xai: "xai",
};

/**
 * Public endpoint (no API key). Returns model ids grouped by provider.
 * OpenRouter id format: "provider/slug" e.g. "anthropic/claude-sonnet-4".
 */
async function fetchOpenRouter(): Promise<Record<string, string[]>> {
  const out: Record<string, string[]> = { anthropic: [], openai: [], gemini: [], xai: [] };
  try {
    const res = await fetch("https://openrouter.ai/api/v1/models");
    if (!res.ok) {
      console.warn("OpenRouter models fetch failed:", res.status);
      return out;
    }
    const data = (await res.json()) as { data?: { id?: string }[] };
    const list = data.data ?? [];
    for (const m of list) {
      const id = m.id;
      if (!id || !id.includes("/")) continue;
      const [prefix, ...rest] = id.split("/");
      const slug = rest.join("/");
      const provider = OPENROUTER_PREFIX[prefix?.toLowerCase() ?? ""];
      if (provider && slug) {
        if (!out[provider]) out[provider] = [];
        out[provider].push(slug);
      }
    }
    for (const p of Object.keys(out)) {
      out[p] = [...new Set(out[p])].sort();
    }
    console.log(
      "OpenRouter (public):",
      Object.entries(out)
        .map(([k, v]) => `${k}=${v.length}`)
        .join(", ")
    );
  } catch (err) {
    console.warn("OpenRouter fetch error:", err);
  }
  return out;
}

const FALLBACKS: Record<string, string[]> = {
  anthropic: ["claude-sonnet-4-20250514", "claude-opus-4"],
  openai: ["gpt-4o", "gpt-4o-mini", "o1"],
  gemini: ["gemini-2.5-flash", "gemini-2.5-pro"],
  xai: ["grok-3", "grok-3-mini", "grok-4-1-fast-reasoning"],
};

async function main(): Promise<void> {
  console.log("Fetching model lists (OpenRouter public + optional provider APIs)...");
  const [openRouter, anthropic, openai, gemini, xai] = await Promise.all([
    fetchOpenRouter(),
    fetchAnthropic(),
    fetchOpenAI(),
    fetchGemini(),
    fetchXAI(),
  ]);

  const pick = (
    provider: keyof typeof FALLBACKS,
    fromApi: string[],
    fromOpenRouter: string[]
  ): string[] => {
    if (fromApi.length) return fromApi;
    if (fromOpenRouter.length) return fromOpenRouter;
    return FALLBACKS[provider];
  };

  const anthropicList = pick("anthropic", anthropic, openRouter.anthropic ?? []);
  const openaiList = pick("openai", openai, openRouter.openai ?? []);
  const geminiList = pick("gemini", gemini, openRouter.gemini ?? []);
  const xaiList = pick("xai", xai, openRouter.xai ?? []);

  const source = (api: number, or: number) =>
    api ? "provider API" : or ? "OpenRouter (public)" : "fallback";
  writeModelConstants(
    "anthropic",
    anthropicList,
    `Anthropic (Claude) model IDs — ${source(anthropic.length, (openRouter.anthropic ?? []).length)}. Run script to refresh.`
  );
  writeModelConstants(
    "openai",
    openaiList,
    `OpenAI model IDs — ${source(openai.length, (openRouter.openai ?? []).length)}. Run script to refresh.`
  );
  writeModelConstants(
    "gemini",
    geminiList,
    `Google Gemini model IDs — ${source(gemini.length, (openRouter.gemini ?? []).length)}. Run script to refresh.`
  );
  writeModelConstants(
    "xai",
    xaiList,
    `xAI (Grok) model IDs — ${source(xai.length, (openRouter.xai ?? []).length)}. Run script to refresh.`
  );

  console.log("Done.");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
